apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: hello-k8s
        env:
        - name: APP_MESSAGE
          value: Hello from the stage environment via Argo CD
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 750m
            memory: 768Mi
