apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s
  labels:
    app: hello-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      imagePullSecrets:
      - name: ecr-regcred
      containers:
      - name: hello-k8s
        image: 776389595347.dkr.ecr.us-west-2.amazonaws.com/ares/spring-boot-hello-k8s:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_MESSAGE
          value: Hello from Kubernetes via Argo CD
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 15
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
